import { existsSync, readdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vitepress'

const __dirname = dirname(fileURLToPath(import.meta.url))

/**
 * Dynamically builds the API sidebar from the files generated by TypeDoc.
 * Run `npm run docs:api` first to populate this.
 */
function getApiSidebar() {
  const apiDir = resolve(__dirname, '../api')
  if (!existsSync(apiDir)) return []

  return readdirSync(apiDir, { withFileTypes: true })
    .filter(
      (entry) =>
        entry.isFile() && entry.name.endsWith('.md') && entry.name !== 'index.md' && entry.name !== 'README.md',
    )
    .map((entry) => {
      const slug = entry.name.replace(/\.md$/, '')
      // "Function.random" → "random"
      const text = slug.includes('.') ? (slug.split('.').at(-1) ?? slug) : slug
      return { text, link: `/api/${slug}` }
    })
}

export default defineConfig({
  title: 'FacileJS',
  description: 'Lightweight JavaScript utilities with simple, beginner-friendly APIs.',

  themeConfig: {
    nav: [
      { text: 'Home', link: '/' },
      { text: 'API', link: '/api/' },
    ],

    sidebar: {
      '/api/': [
        {
          text: 'API Reference',
          items: getApiSidebar(),
        },
      ],
    },

    search: {
      provider: 'local',
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/side-xp/node-facile' }],
  },
})
