import { existsSync, readdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vitepress'

const __dirname = dirname(fileURLToPath(import.meta.url))

/**
 * Dynamically builds the API sidebar from the files generated by TypeDoc.
 * Run `npm run docs:api` first to populate this.
 */
function getApiSidebar() {
  const apiDir = resolve(__dirname, '../api')
  if (!existsSync(apiDir)) return []

  return (
    readdirSync(apiDir, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      // Each "moduleDir" is related to one of the scripts in `src/`
      // For example, `random.ts` will produce a `docs/api/random/` directory
      .map((moduleDir) => {
        const modulePath = resolve(apiDir, moduleDir.name)
        // TypeDoc generates a folder per item type (functions/, variables/, classes/, etc.)
        const items = readdirSync(modulePath, { withFileTypes: true })
          .filter((entry) => entry.isDirectory())
          .flatMap((subDir) =>
            readdirSync(resolve(modulePath, subDir.name), { withFileTypes: true })
              .filter((entry) => entry.isFile() && entry.name.endsWith('.md'))
              // Rename menu: remove *.md extension, add `()` for functions
              .map((entry) => {
                const name = entry.name.replace(/\.md$/, '')
                const text = subDir.name === 'functions' ? `${name}()` : name
                return { text, link: `/api/${moduleDir.name}/${subDir.name}/${name}` }
              }),
          )
        const text = moduleDir.name.charAt(0).toUpperCase() + moduleDir.name.slice(1)
        return { text, items }
      })
  )
}

export default defineConfig({
  title: 'FacileJS',
  description: 'Lightweight JavaScript utilities with simple, beginner-friendly APIs.',
  base: '/node-facile/',

  themeConfig: {
    nav: [
      { text: 'Home', link: '/' },
      { text: 'API', link: '/api/' },
    ],

    sidebar: {
      '/api/': [
        {
          text: 'API Reference',
          items: getApiSidebar(),
        },
      ],
    },

    search: {
      provider: 'local',
    },

    socialLinks: [{ icon: 'github', link: 'https://github.com/side-xp/node-facile' }],
  },
})
