name: Validate

on:
  pull_request:
    branches:
      - develop
      - main

concurrency:
  group: validate-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    with:
      extended: true
